create table employee (
    employee_id int8 generated by default as identity,
    date_of_birth date,
    department_id int4,
     first_name varchar(255),
      gender varchar(255),
      job_title varchar(255),
      last_name varchar(255),
       primary key (employee_id))